### PR TITLE
Add dimensions plugin

### PR DESCRIPTION
**Pull request by wout**
This is the first PR in a series, more will follow. I'm currently working on a fairly complete upload solution for Avram, so I'll be adding everything we need.

This PR adds the `store_dimensions` plugin, and all the surrounding features for it to work. I tried to find the middle ground between how Shrine.rb does it and how you are doing it as much as possible. Please let me know if there is something you don't agree with. 🤓️

As for image analyzers, I decided to implement two:
- [Pixie](https://github.com/watzon/pixie)
- A built-in solution wrapping ImageMagick's `identify` command

I briefly tried implementing [Crymagick](https://github.com/imdrasil/crymagick), but it's last tested on Crystal 0.25.1 and not updated for two years, while specs are failing. Implementing it will be easy, once it's updated and running on Crystal 0.34.0, but that's something for another day. ☺️

Furthermore, I made some personal changes, here is an overview:
- added the [spec_mirror](https://github.com/tilishop/spec_mirror.cr) shard to make specs run automatically using [guardian.cr](https://github.com/f/guardian)
- renamed spec/lib to spec/shrine to play nice with spec_mirror
- moved shrine_spec.cr one level up to play nice with spec_mirror

I find it convenient to have my specs run whenever I save a file in src. That's where spec_mirror comes in. If you don't like those changes, I can revert them and only apply them locally. Or revert everything once I'm done with the features we need.

### CODE REVIEW

**Comment by wout** [comment]
I had this a couple of times before:

```
1) Shrine::Storage::FileSystem#initialize with 0x500 directory permissions sets directory permissions

     Failure: (File.info(subject.expanded_directory)).permissions.value does not equal 320

         actual: 493

       expected: 320

     # spec/shrine/storage/file_system_spec.cr:96
```

Not sure how to get around it, or if it even matters for production situations.

**Comment by igor-alexandrov** [comment]
> I had this a couple of times before:
> 
> ```
> 1) Shrine::Storage::FileSystem#initialize with 0x500 directory permissions sets directory permissions
> 
>      Failure: (File.info(subject.expanded_directory)).permissions.value does not equal 320
> 
>          actual: 493
> 
>        expected: 320
> 
>      # spec/shrine/storage/file_system_spec.cr:96
> ```
> 
> Not sure how to get around it, or if it even matters for production situations.

This happens because `file_system_spec.rb` does not remove created directories after some examples. I will try to fix this later today, so you will be able to rebase.

**Comment by igor-alexandrov** [comment]
Also please take a look at feature/attacher branch: https://github.com/jetrockets/shrine.cr/tree/feature/attacher.

I will try to finish during this weekend.

**Comment by wout** [comment]
That's great, I didn't know you were already so far on the `Attacher` implementation. Are you going to do `Attachment` as well?

In the meantime, I'll make preparations for the following plugins:
- derivatives
- validation
- avram

**Comment by igor-alexandrov** [comment]
`Attachment` is not started yet, but I think that it will be rather easy, compared to `Attacher`.

Also, before doing plugin to Avram, we should think about `Model` plugin (https://shrinerb.com/docs/plugins/model).

**Comment by wout** [comment]
Yeah, `Attachment` looks fairly simple. I'll read up on `Model` this weekend, and `Entity` as well. Thanks for pointing that out.

**Comment by igor-alexandrov** [comment]
@wout dude, I am still working on `Attacher`.  Also I created a Gitter community, feel free to join.

**Comment by wout** [comment]
@igor-alexandrov No worries, I'm occupied with a few other jobs in the following days. This weekend I ran through the whole shrine structure to make sure I fully understand all moving parts. I'll pick up whenever you are ready.

**Comment by wout** [comment]
Voila, rebased and merged. Sorry for the extra commits, I made a mistake merging the shard.yml.

**Comment by igor-alexandrov** [comment]
Hooray! Merged to master, added documentation to Readme and bumped version to 0.5.3.

Great job!

**Pull request merged**
